"""Contracts for one long-lived, full-duplex agent connection.

Unlike ``domain.turn_events``, these streams remain open across multiple speech
turns. ``RealtimeModel*`` events belong to the provider gateway boundary;
``Realtime*`` events are application-facing and carry a ``turn_id`` whenever a
client must correlate output inside the shared connection.
"""

from dataclasses import dataclass
from typing import Literal, TypeAlias

from domain.agent import AgentResult
from domain.interactions import InteractionSource
from domain.tools import ToolCall, ToolCallRecord

# Media sent into the provider session.


@dataclass(frozen=True, slots=True)
class AudioChunk:
    """One raw audio fragment sent to a realtime model session."""

    data: bytes
    mime_type: str = "audio/pcm;rate=16000"


RealtimeActivityDetection = Literal["automatic", "explicit"]
RealtimeRecoveryMode = Literal["transparent", "restart", "none"]
RealtimeConnectionState = Literal["connected", "recovering", "disconnected"]


@dataclass(frozen=True, slots=True)
class RealtimeActivityConfig:
    """Provider-neutral speech activity policy selected for one connection."""

    detection: RealtimeActivityDetection = "automatic"
    start_sensitivity: Literal["high", "low"] | None = None
    end_sensitivity: Literal["high", "low"] | None = None
    prefix_padding_ms: int | None = None
    silence_duration_ms: int | None = None
    interrupt_on_activity: bool = True


@dataclass(frozen=True, slots=True)
class RealtimeSessionOptions:
    """Connection-scoped behavior requested independently of any provider SDK."""

    activity: RealtimeActivityConfig = RealtimeActivityConfig()


@dataclass(frozen=True, slots=True)
class RealtimeSessionCapabilities:
    """Stable media and recovery features implemented by a realtime adapter."""

    input_audio_mime_type: str
    output_audio_mime_type: str
    activity_detection_modes: tuple[RealtimeActivityDetection, ...]
    supports_barge_in: bool
    recovery_mode: RealtimeRecoveryMode


# Provider gateway events received throughout the connection.


@dataclass(frozen=True, slots=True)
class RealtimeModelInputTranscriptDelta:
    """Provider-neutral fragment transcribed from user audio."""

    text: str


@dataclass(frozen=True, slots=True)
class RealtimeModelOutputTranscriptDelta:
    """Provider-neutral fragment transcribed from model audio."""

    text: str


@dataclass(frozen=True, slots=True)
class RealtimeModelAudioDelta:
    """Provider-neutral audio fragment generated by a realtime model."""

    data: bytes
    mime_type: str


@dataclass(frozen=True, slots=True)
class RealtimeModelAudioInterrupted:
    """Signal that pending generated audio must be discarded."""


@dataclass(frozen=True, slots=True)
class RealtimeModelToolCall:
    """Complete tool-call batch requested during an open realtime session."""

    calls: tuple[ToolCall, ...]


@dataclass(frozen=True, slots=True)
class RealtimeModelTurnCompleted:
    """Provider boundary indicating one speech turn has completed."""

    response_id: str


@dataclass(frozen=True, slots=True)
class RealtimeModelActivityStarted:
    """Report provider-observed start of user speech activity."""


@dataclass(frozen=True, slots=True)
class RealtimeModelActivityEnded:
    """Report provider-observed end of user speech activity."""


@dataclass(frozen=True, slots=True)
class RealtimeModelReconnectRequested:
    """Report that the adapter must replace its connection before a deadline."""

    deadline_seconds: float | None = None


@dataclass(frozen=True, slots=True)
class RealtimeModelReconnected:
    """Report that the adapter restored or restarted its provider connection."""

    resumed: bool


RealtimeModelEvent: TypeAlias = (
    RealtimeModelInputTranscriptDelta
    | RealtimeModelOutputTranscriptDelta
    | RealtimeModelAudioDelta
    | RealtimeModelAudioInterrupted
    | RealtimeModelToolCall
    | RealtimeModelTurnCompleted
    | RealtimeModelActivityStarted
    | RealtimeModelActivityEnded
    | RealtimeModelReconnectRequested
    | RealtimeModelReconnected
)


# Application events correlated to one logical turn for realtime clients.


@dataclass(frozen=True, slots=True)
class RealtimeInputTranscriptDelta:
    """User speech transcription fragment exposed to realtime clients."""

    turn_id: str
    text: str


@dataclass(frozen=True, slots=True)
class RealtimeOutputTranscriptDelta:
    """Assistant speech transcription fragment exposed to realtime clients."""

    turn_id: str
    text: str


@dataclass(frozen=True, slots=True)
class RealtimeAudioDelta:
    """Raw assistant audio associated with the active speech turn."""

    turn_id: str
    data: bytes
    mime_type: str


@dataclass(frozen=True, slots=True)
class RealtimeAudioInterrupted:
    """Tell the client to clear buffered playback after a user interruption."""

    turn_id: str


@dataclass(frozen=True, slots=True)
class RealtimeToolStarted:
    """Notify a realtime client before one validated tool batch executes."""

    turn_id: str
    call_id: str
    tool_name: str


@dataclass(frozen=True, slots=True)
class RealtimeToolCompleted:
    """Expose one auditable realtime tool result."""

    turn_id: str
    record: ToolCallRecord


@dataclass(frozen=True, slots=True)
class RealtimeTurnCompleted:
    """Close one logical speech turn without closing the realtime session."""

    turn_id: str
    result: AgentResult
    source: InteractionSource
    job_id: str | None = None
    causation_id: str | None = None


@dataclass(frozen=True, slots=True)
class RealtimeActivityStarted:
    """Expose the start of user activity without leaking provider VAD formats."""

    turn_id: str


@dataclass(frozen=True, slots=True)
class RealtimeActivityEnded:
    """Expose the end of user activity without closing the connection."""

    turn_id: str


@dataclass(frozen=True, slots=True)
class RealtimeReconnectRequested:
    """Tell the client that the provider connection is being recovered."""

    deadline_seconds: float | None = None


@dataclass(frozen=True, slots=True)
class RealtimeReconnected:
    """Tell the client that provider traffic may resume."""

    resumed: bool


RealtimeAgentEvent: TypeAlias = (
    RealtimeInputTranscriptDelta
    | RealtimeOutputTranscriptDelta
    | RealtimeAudioDelta
    | RealtimeAudioInterrupted
    | RealtimeToolStarted
    | RealtimeToolCompleted
    | RealtimeTurnCompleted
    | RealtimeActivityStarted
    | RealtimeActivityEnded
    | RealtimeReconnectRequested
    | RealtimeReconnected
)
