from dataclasses import dataclass
from typing import TypeAlias

from domain.agent import AgentResult
from domain.tools import ToolCall, ToolCallRecord


@dataclass(frozen=True, slots=True)
class AudioChunk:
    """One raw audio fragment sent to a realtime model session."""

    data: bytes
    mime_type: str = "audio/pcm;rate=16000"


@dataclass(frozen=True, slots=True)
class RealtimeModelInputTranscriptDelta:
    """Provider-neutral fragment transcribed from user audio."""

    text: str


@dataclass(frozen=True, slots=True)
class RealtimeModelOutputTranscriptDelta:
    """Provider-neutral fragment transcribed from model audio."""

    text: str


@dataclass(frozen=True, slots=True)
class RealtimeModelAudioDelta:
    """Provider-neutral audio fragment generated by a realtime model."""

    data: bytes
    mime_type: str


@dataclass(frozen=True, slots=True)
class RealtimeModelAudioInterrupted:
    """Signal that pending generated audio must be discarded."""


@dataclass(frozen=True, slots=True)
class RealtimeModelToolCall:
    """Complete tool-call batch requested during an open realtime session."""

    calls: tuple[ToolCall, ...]


@dataclass(frozen=True, slots=True)
class RealtimeModelTurnCompleted:
    """Provider boundary indicating one speech turn has completed."""

    response_id: str


RealtimeModelEvent: TypeAlias = (
    RealtimeModelInputTranscriptDelta
    | RealtimeModelOutputTranscriptDelta
    | RealtimeModelAudioDelta
    | RealtimeModelAudioInterrupted
    | RealtimeModelToolCall
    | RealtimeModelTurnCompleted
)


@dataclass(frozen=True, slots=True)
class RealtimeInputTranscriptDelta:
    """User speech transcription fragment exposed to realtime clients."""

    turn_id: str
    text: str


@dataclass(frozen=True, slots=True)
class RealtimeOutputTranscriptDelta:
    """Assistant speech transcription fragment exposed to realtime clients."""

    turn_id: str
    text: str


@dataclass(frozen=True, slots=True)
class RealtimeAudioDelta:
    """Raw assistant audio associated with the active speech turn."""

    turn_id: str
    data: bytes
    mime_type: str


@dataclass(frozen=True, slots=True)
class RealtimeAudioInterrupted:
    """Tell the client to clear buffered playback after a user interruption."""

    turn_id: str


@dataclass(frozen=True, slots=True)
class RealtimeToolStarted:
    """Notify a realtime client before one validated tool batch executes."""

    turn_id: str
    call_id: str
    tool_name: str


@dataclass(frozen=True, slots=True)
class RealtimeToolCompleted:
    """Expose one auditable realtime tool result."""

    turn_id: str
    record: ToolCallRecord


@dataclass(frozen=True, slots=True)
class RealtimeTurnCompleted:
    """Close one logical speech turn without closing the realtime session."""

    turn_id: str
    result: AgentResult


RealtimeAgentEvent: TypeAlias = (
    RealtimeInputTranscriptDelta
    | RealtimeOutputTranscriptDelta
    | RealtimeAudioDelta
    | RealtimeAudioInterrupted
    | RealtimeToolStarted
    | RealtimeToolCompleted
    | RealtimeTurnCompleted
)
